<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * AwardNominee Model
 * 
 * Represents a nominee within an award category.
 * Nominees can receive votes from users.
 *
 * @property int $id
 * @property int $category_id
 * @property int $award_id
 * @property string $nominee_code
 * @property string $name
 * @property string|null $description
 * @property string|null $image
 * @property int $display_order
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 */
class AwardNominee extends Model
{
    protected $table = 'award_nominees';
    protected $primaryKey = 'id';
    public $incrementing = true;
    public $timestamps = true;

    protected $fillable = [
        'category_id',
        'award_id',
        'nominee_code',
        'name',
        'description',
        'image',
        'display_order',
    ];

    /**
     * Boot method to handle model events.
     */
    protected static function boot()
    {
        parent::boot();

        // Auto-generate nominee_code when creating a new nominee
        static::creating(function ($nominee) {
            if (empty($nominee->nominee_code)) {
                $nominee->nominee_code = self::generateNomineeCode($nominee->award_id);
            }
        });
    }

    /**
     * Generate a nominee code using award code and sequence number.
     * 
     * @param int $awardId
     * @return string
     */
    public static function generateNomineeCode(int $awardId): string
    {
        $award = Award::find($awardId);
        $awardCode = $award ? $award->award_code : 'AW'; // Fallback to AW
        
        // Use count + 1 for the next number
        $count = self::where('award_id', $awardId)->count();
        $nextNumber = $count + 1;
        
        return $awardCode . $nextNumber;
    }

    /**
     * Find a nominee by their unique code.
     */
    public static function findByCode(string $code): ?self
    {
        return self::where('nominee_code', strtoupper($code))->first();
    }

    protected $casts = [
        'category_id' => 'integer',
        'award_id' => 'integer',
        'display_order' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    /**
     * Get the category that owns this nominee.
     */
    public function category()
    {
        return $this->belongsTo(AwardCategory::class, 'category_id');
    }

    /**
     * Get the award that owns this nominee.
     */
    public function award()
    {
        return $this->belongsTo(Award::class, 'award_id');
    }

    /**
     * Get all votes for this nominee.
     */
    public function votes()
    {
        return $this->hasMany(AwardVote::class, 'nominee_id');
    }

    /**
     * Get total number of votes received by this nominee.
     */
    public function getTotalVotes(): int
    {
        return (int) $this->votes()
                    ->where('status', 'paid')
                    ->sum('number_of_votes');
    }

    /**
     * Get total revenue generated by this nominee.
     * 
     * @param float|null $costPerVote Optional cost per vote, fetches from category if not provided
     */
    public function getTotalRevenue(?float $costPerVote = null): float
    {
        return (float) $this->votes()
                    ->where('status', 'paid')
                    ->sum('gross_amount');
    }

    /**
     * Get all paid votes for this nominee.
     */
    public function getPaidVotes()
    {
        return $this->votes()
                    ->where('status', 'paid')
                    ->get();
    }

    /**
     * Get nominee details with vote statistics.
     */
    public function getDetailsWithStats(): array
    {
        $category = $this->category;
        $costPerVote = $category ? $category->cost_per_vote : 0;

        return [
            'id' => $this->id,
            'nominee_code' => $this->nominee_code,
            'category_id' => $this->category_id,
            'award_id' => $this->award_id,
            'name' => $this->name,
            'description' => $this->description,
            'image' => $this->image,
            'display_order' => $this->display_order,
            'total_votes' => $this->getTotalVotes(),
            'total_revenue' => $this->getTotalRevenue($costPerVote),
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
        ];
    }

    /**
     * Scope to order by display order.
     */
    public function scopeOrdered($query)
    {
        return $query->orderBy('display_order');
    }

    /**
     * Scope to get nominees by category.
     */
    public function scopeByCategory($query, int $categoryId)
    {
        return $query->where('category_id', $categoryId);
    }

    /**
     * Scope to get nominees for a specific award.
     */
    public function scopeForAward($query, $awardId)
    {
        return $query->where('award_id', $awardId);
    }
}
